export const GET_QUESTIONS = 'GET_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const GET_USERS = 'GET_USERS';
export const SAVE_USER_ANSWER = 'SAVE_USER_ANSWER';
